apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      script: |
        #!/usr/bin/env sh
        if [ -d "$(workspaces.source.path)" ] ; then
          rm -rf "$(workspaces.source.path)"/*
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eslint
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: node:20-alpine
      workingDir: $(workspaces.source.path)
      script: |
        npm ci
        npm run lint

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jest-test
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: node:20-alpine
      workingDir: $(workspaces.source.path)
      script: |
        npm ci
        npm test